force-app/main/default/objects/Seminar__c/Seminar__c.object-meta.xml
<CustomObject>
    <label>Seminar</label>
    <nameField>
        <label>Seminar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seminars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seminar__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeightCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seminar__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seminar__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Speaker</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seminar__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Venue</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SearchSeminarsCon.cls
public WITH SHARING class SearchSeminarsCon {
	@AuraEnabled
    Public STATIC List<Seminar__c> returnAllSeminars()
    {
        System.debug('lightning call ==> ');
        return [select Id, Name, Category__c, Speaker__c, Venue__c, Day__c, Time__c from Seminar__c LIMIT 10];
    }
    
    @AuraEnabled
    Public STATIC List<Seminar__c> returnSeminarsByCategory(String Category)
    {
        System.debug('lightning call ==> ');
        return [select Id, Name, Category__c, Speaker__c, Venue__c, Day__c, Time__c from Seminar__c WHERE Category__c =: Category LIMIT 100];
    }
}