force-app/main/default/objects/Volunteer__c/Volunteer__c.object-meta.xml
<CustomObject>
    <label>Volunteer</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Volunteer Nunmber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer__c/fields/Height_in_Cms__c.field-meta.xml
<CustomField>
    <fullName>Height_in_Cms__c</fullName>
    <label>Height in Cms</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Volunteer__c/fields/Volunteer_Name__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Name__c</fullName>
    <label>Volunteer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Volunteer__c/fields/Weight_in_kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_in_kg__c</fullName>
    <label>Weight in kg</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VolunteerCreateCon.cls
public WITH SHARING class VolunteerCreateCon {
	
    @AuraEnabled
    Public STATIC Id createVolunteer(String volName, Integer volHeight, Integer volWeight, String volMobile, String volEmail)
    {
        Volunteer__c volForIns = new Volunteer__c(Volunteer_Name__c=volName, Height_in_Cms__c=volHeight, Weight_in_kg__c=volWeight, Mobile__c=volMobile, Email__c=volEmail);
        insert volForIns;
        return volForIns.Id;
    }
    
}