force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Agreement__c/Rental_Agreement__c.object-meta.xml
<CustomObject>
    <label>Rental Agreement</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Rental Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Statement__c/fields/Rental_Agreement_del__c.field-meta.xml
<CustomField>
    <fullName>Rental_Agreement_del__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rental Agreement</label>
    <referenceTo>Rental_Agreement__c</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Statement__c/fields/Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_amount__c</fullName>
    <formula>Amount__c  +  Additional_Fees__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Rollup_Methods.cls
public class Rollup_Methods {
    
    public static void rollupStatementsToRentalAgreement(List<Statement__c> newList)
    {
        Set<id> rentalAgreementSet=new Set<id>();
        for(Statement__c s:newList)
        {
            rentalAgreementSet.add(s.Rental_Agreement_del__c);
            
        }
        //this list will store the rental Agreement records which needs to be updates
        List<Rental_Agreement__c> rentalUpdates=new List<Rental_Agreement__c>();
        //aggregate query to sum total amount from statement
        System.debug('rentalAgreementSet====='+rentalAgreementSet);
        for(AggregateResult ar:[select sum(Total_amount__c)totalInvoice,Rental_Agreement_del__c from Statement__c where Rental_Agreement_del__c IN :rentalAgreementSet group by Rental_Agreement_del__c])
        {
            Rental_Agreement__c r=new Rental_Agreement__c(id=String.valueOf(ar.get('Rental_Agreement__c')));
            r.Total_Invoiced__c=double.valueOf(ar.get('totalInvoice'));
            rentalUpdates.add(r);
        }
        if(!rentalUpdates.isEmpty())
        {
            update rentalUpdates;
        }
    }

     public static void rollupPaymentsToRentalAgreement(Map<id,Payment__c> newMap)
     {
         Set<Id> rentalAgreementSet =new Set<id>();
         for(Payment__c p : [SELECT id,Statement__r.Rental_Agreement_del__c FROM Payment__c where Id IN :newMap.keySet()])
         {
             rentalAgreementSet.add(p.Statement__r.Rental_Agreement_del__c);
         }
         List<Rental_Agreement__c> rentalUpdates=new List<Rental_Agreement__c>();
         
         for(AggregateResult ar:[SELECT sum(Amount__c)totalPaid,Statement__r.Rental_Agreement_del__c FROM Payment__c where Statement__r.Rental_Agreement_del__c IN :rentalAgreementSet group by Statement__r.Rental_Agreement_del__c  ])
         {
             Rental_Agreement__c r = new Rental_Agreement__c(id=string.valueOf(ar.get('ra')));
             r.Total_Payments__c=double.valueOf(ar.get('totalPaid'));
             rentalUpdates.add(r);
         }
         
         if(!rentalUpdates.isEmpty())
         {
             update rentalUpdates;
         }
    }
}